def ask_for_sales
  puts "Enter the sales generated by the employee: "
  gets.chomp.to_f
end

def ask_for_advanced_pay
  puts "Enter the amount of advanced payment or "
  puts "type 0 if no advanced payment was given"
  gets.chomp.to_f
end

def determine_comission_rate(sales)
  if sales < 10000
    rate = 0.10
  elsif sales >= 10000 and sales <= 14999.99
    rate = 0.12
  elsif sales >= 15000 and sales <= 17999.99
    rate = 0.14
  elsif sales >= 18000 and sales <= 21999.99
    rate = 0.16
  else
    rate = 0.18
  end
end

def calculate_pay(sales, comission_rate, advanced_pay)
  comission = sales * comission_rate
  net_pay = comission - advanced_pay
end

def determine_reimburse(pay)
  if pay < 0
    puts "The salesperson must reimburse $#{pay.abs} to the company."
  else
    puts "Nothing has to be reimbursed to the company."
  end
end

def print_pay(pay)
  puts "The comission is $#{pay}"
end

# Program Starts
sales = ask_for_sales()
advanced_pay = ask_for_advanced_pay()
comission_rate = determine_comission_rate(sales)
pay = calculate_pay(sales, comission_rate, advanced_pay)
print_pay(pay)
determine_reimburse(pay)
