def ask_for_sales
  puts "Enter the sales generated by the employee: "
  gets.chomp.to_f
end

def ask_for_advanced_pay
  puts "Enter the amount of advanced pay or "
  puts "type 0 if no advancedpay was given"
  gets.chomp.to_f
end

def determine_comission_rate(sales)
  if sales < 10000
    rate = 0.10
  elsif sales >= 10000 and sales <= 14999.99
    rate = 0.12
  elsif sales >= 15000 and sales <= 17999.99
    rate = 0.14
  elsif sales >= 18000 and sales <= 21999.99
    rate = 0.16
  else
    rate = 0.18
  end
end
